/**
 * This file aggregates all processor factories
 * Auto-generated by codegen - DO NOT EDIT MANUALLY
 */

import { type ProcessorFactory, type ProcessorRecord } from "document-drive";
import { type PHDocumentHeader } from "document-model";

// Import processor factories here as they are generated
import { documentEditorBuilderCustomComponentProcessorFactory } from "./document-editor-builder-custom-component/factory.js";
import { documentEditorBuilderGeneratorProcessorFactory } from "./document-editor-builder-generator/factory.js";

export const processorFactory = () => {
  // Initialize all processor factories once with the module
  const factories: Array<ProcessorFactory> = [];

  // Add processors here as they are generated
  factories.push(documentEditorBuilderGeneratorProcessorFactory());
  factories.push(documentEditorBuilderCustomComponentProcessorFactory());

  // Return the inner function that will be called for each drive
  return async (driveHeader: PHDocumentHeader): Promise<ProcessorRecord[]> => {
    const processors: ProcessorRecord[] = [];

    // Call each cached factory with the driveHeader
    for (const factory of factories) {
      const factoryProcessors = await factory(driveHeader);
      processors.push(...factoryProcessors);
    }

    return processors;
  };
};
